version: '3'

services:
  db: 
    env_file:
      - database.env
    volumes:
      - ./data:/data
      - ./sql_code:/sql_code
    image: postgres:11
    ports: 
      - 5432:5432

  dataengineering: 
    env_file:
      - database.env
    build: ./python_code
    volumes: 
      - ./python_code:/python_code
    ports:
      - 80:5000
    depends_on:
      - db
